[build]
  command = "pnpm build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA fallback (Vite/React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  # The command that runs your app (Vite)
  command = "pnpm dev"        # or "npm run dev"
  port = 5173                 # your Vite port
  framework = "#static"       # let Netlify proxy to your dev server