[build]
  command = "pnpm build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA fallback (Vite/React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200